"""
SFT training script for efficient math reasoning.

Fine-tunes on the efficient examples generated by generate_efficient_data.py.
Uses the existing SFT infrastructure with FromConversationFileBuilder.
Runs evaluation automatically after training completes.
"""

import asyncio
import logging
import os
from datetime import datetime

import chz
from tinker_cookbook import cli_utils, model_info
from tinker_cookbook.recipes.math_efficiency.eval import (
    print_results_table,
    run_evaluation,
)
from tinker_cookbook.supervised.data import FromConversationFileBuilder
from tinker_cookbook.supervised.train import Config, main
from tinker_cookbook.supervised.types import ChatDatasetBuilderCommonConfig

logger = logging.getLogger(__name__)


@chz.chz
class CLIConfig:
    """Configuration for SFT training on efficient examples."""

    # Model configuration
    model_name: str = "Qwen/Qwen3-8B"
    lora_rank: int = 128
    renderer_name: str | None = None
    load_checkpoint_path: str | None = None

    # Data configuration
    data_path: str = "/tmp/gsm8k_efficient.jsonl"

    # Training hyperparameters
    learning_rate: float = 5e-5
    num_epochs: int = 2
    batch_size: int = 8
    max_length: int = 2048

    # Logging configuration
    log_path: str | None = None
    wandb_project: str | None = "math-efficiency-interview"
    wandb_name: str | None = None  # Defaults to "sft-efficient-{model}"

    # Checkpointing
    save_every: int = 20
    eval_every: int = 10

    # Service configuration
    base_url: str | None = None

    behavior_if_log_dir_exists: cli_utils.LogdirBehavior = "ask"

    # Final evaluation config
    run_final_eval: bool = True
    eval_num_problems: int = 10
    eval_samples_per_problem: int = 4


async def cli_main(cli_config: CLIConfig):
    """Convert CLI config to full config and run training."""
    # Determine renderer
    renderer_name = cli_config.renderer_name or model_info.get_recommended_renderer_name(
        cli_config.model_name
    )

    # Generate log path and run name
    model_name_safe = cli_config.model_name.replace("/", "-")
    timestamp = datetime.now().strftime('%Y%m%d-%H%M')
    run_name = f"sft-{model_name_safe}-{timestamp}"

    if cli_config.log_path is not None:
        log_path = cli_config.log_path
    else:
        log_path = f"/tmp/tinker-examples/math_efficiency_sft/{run_name}"

    wandb_name = cli_config.wandb_name or run_name

    # Create dataset builder using FromConversationFileBuilder
    dataset_builder = FromConversationFileBuilder(
        file_path=cli_config.data_path,
        test_size=0,  # No test split for this training
        shuffle_seed=42,
        common_config=ChatDatasetBuilderCommonConfig(
            model_name_for_tokenizer=cli_config.model_name,
            renderer_name=renderer_name,
            batch_size=cli_config.batch_size,
            max_length=cli_config.max_length,
        ),
    )

    # Create full config
    config = Config(
        log_path=log_path,
        model_name=cli_config.model_name,
        load_checkpoint_path=cli_config.load_checkpoint_path,
        dataset_builder=dataset_builder,
        learning_rate=cli_config.learning_rate,
        num_epochs=cli_config.num_epochs,
        lora_rank=cli_config.lora_rank,
        base_url=cli_config.base_url,
        save_every=cli_config.save_every,
        eval_every=cli_config.eval_every,
        wandb_project=cli_config.wandb_project,
        wandb_name=wandb_name,
    )

    # Check log directory
    cli_utils.check_log_dir(log_path, behavior_if_exists=cli_config.behavior_if_log_dir_exists)

    logger.info(f"Starting SFT training on efficient examples from {cli_config.data_path}")
    logger.info(f"Log path: {log_path}")

    # Run training
    await main(config)

    # Run final evaluation
    if cli_config.run_final_eval:
        logger.info("")
        logger.info("=" * 60)
        logger.info("Running final evaluation on trained model")
        logger.info("=" * 60)

        # Read checkpoint path from checkpoints.jsonl
        checkpoints_file = os.path.join(log_path, "checkpoints.jsonl")
        checkpoint_path = None
        if os.path.exists(checkpoints_file):
            import json
            with open(checkpoints_file, "r") as f:
                for line in f:
                    ckpt = json.loads(line)
                    if ckpt.get("name") == "final":
                        checkpoint_path = ckpt.get("sampler_path")
                        break

        if not checkpoint_path:
            logger.error("Could not find final checkpoint path")
            return

        eval_output_path = os.path.join(log_path, "eval_results.json")

        eval_results = await run_evaluation(
            model_name=cli_config.model_name,
            checkpoint_path=checkpoint_path,
            num_problems=cli_config.eval_num_problems,
            samples_per_problem=cli_config.eval_samples_per_problem,
            max_tokens=cli_config.max_length,
            temperature=1.0,
            base_url=cli_config.base_url,
            renderer_name=renderer_name,
        )

        print_results_table(eval_results)

        # Save results
        with open(eval_output_path, "w") as f:
            f.write(eval_results.model_dump_json(indent=2))
        logger.info(f"Evaluation results saved to: {eval_output_path}")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    cli_config = chz.entrypoint(CLIConfig)
    asyncio.run(cli_main(cli_config))
